# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comms.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comms.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x63omms.proto\x12\x08tutorial\"0\n\x04INFO\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x14\n\x04\x44\x41TA\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t'
)




_INFO = _descriptor.Descriptor(
  name='INFO',
  full_name='tutorial.INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.INFO.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='tutorial.INFO.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='tutorial.INFO.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=73,
)


_DATA = _descriptor.Descriptor(
  name='DATA',
  full_name='tutorial.DATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tutorial.DATA.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['INFO'] = _INFO
DESCRIPTOR.message_types_by_name['DATA'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

INFO = _reflection.GeneratedProtocolMessageType('INFO', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'comms_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.INFO)
  })
_sym_db.RegisterMessage(INFO)

DATA = _reflection.GeneratedProtocolMessageType('DATA', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'comms_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.DATA)
  })
_sym_db.RegisterMessage(DATA)


# @@protoc_insertion_point(module_scope)
